/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package washer;

import org.junit.Test;
//import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        //WasherPlugin classUnderTest = new WasherPlugin();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
